### PR TITLE
Added support of search related models by tags slugs.

### PR DESCRIPTION
**Pull request by a-komarev**
Added support for tags with SluggableBehavior.

### CODE REVIEW

**Comment by a-komarev** [comment]
@creocoder Alexander, is there a chance to add this code to repository, or it isn't good?

**Comment by creocoder** [comment]
@a-komarev Hi, we will implement such feature another more elegant way. I'm still thinking about implementation.

**Comment by a-komarev** [comment]
Okay, thanks.
I have thought that it's very hardcoded one, but wont make changes in your current codebase.

**Comment by creocoder** [comment]
@a-komarev If short more elegant way would be introducing `TaggableQuery::tagSearchAttribute`. If it null `TaggableBehavior::tagNameAttribute` will be used. Also `TaggableQuery::allTagNames()` should be renamed to `TaggableQuery::allTags()`, etc. Currently i'm thinking about that solution.

**Comment by creocoder** [comment]
@a-komarev Also this non BC changes will lead us to increase extension version since i use semver for mine extension. This is why everything should be carefully thought out.

**Comment by a-komarev** [comment]
@creocoder Changing a version is a right decision! Your description seems good for me.

**Comment by creocoder** [comment]
@a-komarev After some though i think we can go next way:

- rename `allTagNames()` to `allTags()`
- rename `anyTagNames()` to `anyTags()`
- rename `relatedByTagNames()` to `relatedByTags()`
- introduce second param for all those methods

```php
public function anyTags($values, $attribute = null) { ... }
public function allTags($values, $attribute = null) { ... }
public function relatedByTags($values, $attribute = null) { ... }
```

If `$attribute` is `null` than `TaggableBehavior::tagNameAttribute` will be used. Its better than mine previous suggestion by several reasons.

What you think about that?

**Comment by a-komarev** [comment]
It will be more flexible I think, because we can get tags by slugs or by names in different parts of application. And if there will be attribute in Behavior's configuration we will lose this feature.

**Comment by creocoder** [comment]
@a-komarev Feature implemented in `develop` branch which was created for 2.0 version. Release is soon.

**Comment by a-komarev** [comment]
Thank you. Gonna test it ASAP.

**Comment by creocoder** [comment]
@a-komarev Test better 2.0 since its already released. Read new documentation to test feature.

**Comment by a-komarev** [comment]
It's working as expected! I haven't found any problems.
Thanks a lot, you've done a very good job!

**Pull request closed without merging**
